### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by vedantrathore** [vedantrathore/bookmyshow-cli#5]

**Comment by aditya-konarde** [comment]
Would like to work on this. Where do you want the documentation to be added?

**Comment by vedantrathore** [comment]
Just update the readme file with how to install and contributing guidlines

**Comment by Mymoza** [comment]
I did a commit, hope this is what you expected! Let me know.

**Comment by pranavgoel25** [comment]
I would like to work on this.

I made a pull request. Hope it helps!

49e3661a41bab9476e9b2f3ca7148932cd16bac1

**Comment by vedantrathore** [comment]
@Mymoza that's perfect. 
@pranavgoel25 since there was already someone on this issue, so I couldn't accept your pull request.
